delete from recipe_instruction;
delete from recipe_ingredient;
delete from recipes;
delete from users;
insert into users values (1, 'Harry', 'Louis', 'halou', 'myPassword2', 'Harry Louis', 'harlou@gmail.com'), (2, 'Simon', 'James', 'sijames', 'ineedapassword', 'Simon James', 'simjam@outlook.com'), (3, 'Alexandra', 'Dixson', 'aldix', 'IGotThePower', 'Alexandra Dixson', 'alex234@madisoncollege.edu'), (4, 'Kevin', 'Edwards', 'kevedw', 'LetItBe', 'Kevin Edwards', 'keved@gmail.com'), (5, 'Ashley', 'Douglas', 'ashdoug', 'password', 'Ashley Douglas', 'ash347@outlook.com'), (6, 'Cassandra', 'Walker', 'caswal', 'PinkFluffyBunny', 'Cassandra Walker', 'caswal@madisoncollege.edu'), (7, 'Joseph', 'Wyatt', 'joswya', 'YetAnotherPassword', 'Joseph Wyatt', 'joswya@gmail.com'), (8, 'Issac', 'Werner', 'iswer', 'coolPassword369', 'Issac Werner', 'iswer@outlook.com'), (9, 'Angela', 'Blanchard', 'anblan', 'Idontknow', 'Angela Blanchard', 'anblan@madisoncollege.edu'), (10, 'Fred', 'Smith', 'frsmith', 'whatsthepassword', 'Fred Smith', 'smithfred@yahoo.com');
INSERT INTO recipes VALUES (1,'Homemade Chicken Alfredo',1,1196,50,14,105,35,'Dinner',2), (2,'Delicious Egg Salad (Easy)',2,334,13,2,32,35,'Lunch',4),(3,'Hashbrown Breakfast Casserole',null,312,19,5,24,70,'Breakfast',6);
INSERT INTO recipe_ingredient VALUES (1,'Chicken breast ','1',NULL,1),(2,'Fettuccini noodles','1','pound',1),(3,'Extra virgin olive oil','3','tbsp',1),(4,'Chicken stock','1 1/2','cup',1),(5,'Garlic clove','1',NULL,1),(6,'Heavy cream','1 1/2','cup',1),(7,'Parmesan','1','cup',1),(8,'Parsley','1/4','cup',1),(9,'Lemon (Juice)','1',NULL,1), (10,'Eggs','8',NULL,2),(11,'Mayonnaise','1/2','cup',2),(12,'Chopped Green Onion','1/4','cup',2),(13,'Yellow mustard','1','teaspoon',2),(14,'Paprika','1/4','teaspoon',2),(15,'Salt and pepper to taste',NULL,NULL,2),(16,'Frozen hashbrowns, thawed ','1','bag',3),(17,'Salted butter, melted','1/4','cup',3),(18,'Eggs','3',NULL,3),(19,'Milk','1','cup',3),(20,'Salt','1','teaspoon',3),(21,'Shredded mild cheddar cheese','1','cup',3),(22,'Shredded swiss cheese','1','cup',3),(23,'Diced ham','1','cup',3);

INSERT INTO recipe_instruction VALUES (1,'Wash Chicken breast then pat dry. Cut into thin strips. ',1,1),(2,'Boil fettucine pasta according to box instructions, when ready se aside.',2,1),(3,'Heat a non-stick pan with olive oil and add chicken strips. Cook for 6-7 minutes on each side until golden brown, on medium heat. Remove chicken from pan when ready and set aside.',3,1),(4,'Add minced garlic and saute for 3 minutes. Deglaze pan with chicken stock, add lemon juice and bring to boil.',4,1),(5,'Add heavy cream, then add the cooked pasta and chicken.',5,1),(6,'Add parmesan and stir until everything is well combined.',6,1),(7,'Sprinkle with parsley and enjoy!',7,1),(8,'Place eggs in a saucepan and cover with cold water. Bring water to a boil and immediately remove from heat. Cover and let eggs stand in hot water for 10 - 12 minutes. Remove from hot water, cool, peel, and chop.',1,2),(9,'Place chopped eggs in a bowl, stir in mayonnaise, green onion, and mustard. Season with paprika, salt, and pepper. Stir and serve on your favorite bread or crackers.',2,2),(10,'Preheat oven to 375 degrees. Spray 9-inch pie pan with non-stick cooking spray.',1,3),(11,'Place hashbrowns in pan and drizzle with melted butter. Bake 20 minutes and remove from oven.',2,3),(12,'Combine eggs, milk and salt in a medium bowl and wisk thoroughly. Set aside. ',3,3),(13,'Evenly layer cheddar cheese, swiss cheese and ham on top of cooked hashbrowns. Pour egg mixtue over top. ',4,3),(14,'Bake at 350 degrees for 40 minutes or until eggs are set. Remove from oven and let sit for 3 to 5 minutes. Serve warm. ',5,3);


